#import <Foundation/Foundation.h>

@class LAActivator;

#define LA_ACTIVATOR_IPC_EXTERN extern __attribute__((visibility("hidden")))

LA_ACTIVATOR_IPC_EXTERN NSString *const LAActivatorIPCServerName;

LA_ACTIVATOR_IPC_EXTERN NSString *const LAActivatorIPCMessageAvailableEventNames;
LA_ACTIVATOR_IPC_EXTERN NSString *const LAActivatorIPCMessageHasEvent;
LA_ACTIVATOR_IPC_EXTERN NSString *const LAActivatorIPCMessageAvailableListenerNames;
LA_ACTIVATOR_IPC_EXTERN NSString *const LAActivatorIPCMessageHasListener;
LA_ACTIVATOR_IPC_EXTERN NSString *const LAActivatorIPCMessageAssignedListenerNames;
LA_ACTIVATOR_IPC_EXTERN NSString *const LAActivatorIPCMessageEventsAssignedToListener;
LA_ACTIVATOR_IPC_EXTERN NSString *const LAActivatorIPCMessageAssignEvent;
LA_ACTIVATOR_IPC_EXTERN NSString *const LAActivatorIPCMessageUnassignEvent;
LA_ACTIVATOR_IPC_EXTERN NSString *const LAActivatorIPCMessageApplicationIsBlacklisted;
LA_ACTIVATOR_IPC_EXTERN NSString *const LAActivatorIPCMessageSetApplicationBlacklisted;
LA_ACTIVATOR_IPC_EXTERN NSString *const LAActivatorIPCMessageAvailableProfileNames;
LA_ACTIVATOR_IPC_EXTERN NSString *const LAActivatorIPCMessageCurrentProfileName;
LA_ACTIVATOR_IPC_EXTERN NSString *const LAActivatorIPCMessageSetCurrentProfileName;

LA_ACTIVATOR_IPC_EXTERN NSString *const LAActivatorIPCMessageEventIsHidden;
LA_ACTIVATOR_IPC_EXTERN NSString *const LAActivatorIPCMessageEventRequiresAssignment;
LA_ACTIVATOR_IPC_EXTERN NSString *const LAActivatorIPCMessageCompatibleModesForEvent;
LA_ACTIVATOR_IPC_EXTERN NSString *const LAActivatorIPCMessageEventIsCompatibleWithMode;
LA_ACTIVATOR_IPC_EXTERN NSString *const LAActivatorIPCMessageEventSupportsUnlockingDeviceToSend;
LA_ACTIVATOR_IPC_EXTERN NSString *const LAActivatorIPCMessageEventSupportsRemoval;
LA_ACTIVATOR_IPC_EXTERN NSString *const LAActivatorIPCMessageEventSupportsConfiguration;

LA_ACTIVATOR_IPC_EXTERN NSString *const LAActivatorIPCMessageListenerInfoDictionaryValue;
LA_ACTIVATOR_IPC_EXTERN NSString *const LAActivatorIPCMessageListenerRequiresAssignment;
LA_ACTIVATOR_IPC_EXTERN NSString *const LAActivatorIPCMessageCompatibleModesForListener;
LA_ACTIVATOR_IPC_EXTERN NSString *const LAActivatorIPCMessageListenerIsCompatibleWithMode;
LA_ACTIVATOR_IPC_EXTERN NSString *const LAActivatorIPCMessageListenerIsCompatibleWithEvent;
LA_ACTIVATOR_IPC_EXTERN NSString *const LAActivatorIPCMessageListenerNeedsPoweredDisplay;
LA_ACTIVATOR_IPC_EXTERN NSString *const LAActivatorIPCMessageExclusiveAssignmentGroupsForListener;
LA_ACTIVATOR_IPC_EXTERN NSString *const LAActivatorIPCMessageListenerNamesAreMutuallyCompatible;
LA_ACTIVATOR_IPC_EXTERN NSString *const LAActivatorIPCMessageListenerSupportsRemoval;
LA_ACTIVATOR_IPC_EXTERN NSString *const LAActivatorIPCMessageListenerSupportsConfiguration;

LA_ACTIVATOR_IPC_EXTERN NSString *const LAActivatorIPCMessageLocalizedTitleForEventName;
LA_ACTIVATOR_IPC_EXTERN NSString *const LAActivatorIPCMessageLocalizedTitleForListenerName;
LA_ACTIVATOR_IPC_EXTERN NSString *const LAActivatorIPCMessageLocalizedTitleForListenerNames;
LA_ACTIVATOR_IPC_EXTERN NSString *const LAActivatorIPCMessageLocalizedGroupForEventName;
LA_ACTIVATOR_IPC_EXTERN NSString *const LAActivatorIPCMessageLocalizedGroupForListenerName;
LA_ACTIVATOR_IPC_EXTERN NSString *const LAActivatorIPCMessageLocalizedDescriptionForEventName;
LA_ACTIVATOR_IPC_EXTERN NSString *const LAActivatorIPCMessageLocalizedDescriptionForListenerName;

LA_ACTIVATOR_IPC_EXTERN NSString *const LAActivatorIPCKeyOK;
LA_ACTIVATOR_IPC_EXTERN NSString *const LAActivatorIPCKeyValue;
LA_ACTIVATOR_IPC_EXTERN NSString *const LAActivatorIPCKeyEventName;
LA_ACTIVATOR_IPC_EXTERN NSString *const LAActivatorIPCKeyEventMode;
LA_ACTIVATOR_IPC_EXTERN NSString *const LAActivatorIPCKeyListenerName;
LA_ACTIVATOR_IPC_EXTERN NSString *const LAActivatorIPCKeyListenerNames;
LA_ACTIVATOR_IPC_EXTERN NSString *const LAActivatorIPCKeyDisplayIdentifier;
LA_ACTIVATOR_IPC_EXTERN NSString *const LAActivatorIPCKeyBlacklisted;
LA_ACTIVATOR_IPC_EXTERN NSString *const LAActivatorIPCKeyProfileName;
LA_ACTIVATOR_IPC_EXTERN NSString *const LAActivatorIPCKeyInfoDictionaryKey;

#undef LA_ACTIVATOR_IPC_EXTERN

__attribute__((visibility("hidden")))
@interface LAActivatorIPCClient : NSObject
- (NSArray *)arrayValueForMessageName:(NSString *)messageName userInfo:(NSDictionary *)userInfo;
- (NSString *)stringValueForMessageName:(NSString *)messageName userInfo:(NSDictionary *)userInfo;
- (id)propertyListValueForMessageName:(NSString *)messageName userInfo:(NSDictionary *)userInfo;
- (BOOL)boolValueForMessageName:(NSString *)messageName userInfo:(NSDictionary *)userInfo defaultValue:(BOOL)defaultValue;
- (NSArray *)eventsValueForMessageName:(NSString *)messageName userInfo:(NSDictionary *)userInfo;
- (BOOL)sendMessageName:(NSString *)messageName userInfo:(NSDictionary *)userInfo;
@end

__attribute__((visibility("hidden")))
@interface LAActivatorIPCServer : NSObject
- (instancetype)initWithActivator:(LAActivator *)activator;
- (void)start;
@end
